// Questionnaire data — wijzig dit bestand om de vragenlijst aan te passen.
// Let op: prompts.js verwijst naar vraag-IDs uit dit bestand.

export const QUESTIONNAIRE_ID = 'ai-scan-advocaten-v1';

export const SECTIONS = [
  { id: "org", title: "Organisatie & Governance", icon: "\u2696\uFE0F",
    subtitle: "Hoe is uw kantoor georganiseerd rondom technologie en AI?",
    questions: [
      { id: "org_size", text: "Hoeveel advocaten/juristen werken er bij uw kantoor?", type: "select",
        options: [
          { v: "solo", l: "1" },
          { v: "small", l: "2 \u2013 10" },
          { v: "medium", l: "11 \u2013 50" },
          { v: "large", l: "51 \u2013 200" },
          { v: "xlarge", l: "200+" }
        ] },
      { id: "org_specialisms", text: "Rechtsgebied(en)?", type: "multi",
        options: [
          { v: "corporate", l: "Ondernemingsrecht" },
          { v: "ma", l: "M&A" },
          { v: "civil", l: "Civiel recht" },
          { v: "employment", l: "Arbeidsrecht" },
          { v: "ip", l: "IE / IT-recht" },
          { v: "tax", l: "Fiscaal recht" },
          { v: "real_estate", l: "Vastgoedrecht" },
          { v: "criminal", l: "Strafrecht" },
          { v: "family", l: "Personen- en familierecht" },
          { v: "admin", l: "Bestuursrecht" },
          { v: "insolvency", l: "Insolventierecht" },
          { v: "international", l: "Internationaal recht en EU-recht" },
          { v: "personal_injury", l: "Letselschade" },
          { v: "education", l: "Onderwijsrecht" },
          { v: "privacy", l: "Privacyrecht" },
          { v: "procurement", l: "Aanbestedingsrecht" },
          { v: "disciplinary", l: "Tuchtrecht" },
          { v: "cassation", l: "Cassatie" },
        ] },
      { id: "org_ai_owner", text: "Is er binnen uw kantoor iemand aangewezen die verantwoordelijk is voor AI-beleid en -beslissingen?", type: "select",
        options: [{ v: "none", l: "Nee, niemand specifiek" }, { v: "informal", l: "Informeel, iemand pakt het er bij" }, { v: "assigned", l: "Ja, een aangewezen persoon" }, { v: "team", l: "Ja, een dedicated team of commissie" }],
        scoring: { none: { orde: -2, avg: -2, aiact: -2 }, informal: { orde: -1, avg: -1, aiact: -1 }, assigned: { orde: 2, avg: 2, aiact: 2 }, team: { orde: 3, avg: 3, aiact: 3 } } },
      { id: "org_policy", text: "Beschikt uw kantoor al over een AI-beleid of -richtlijn?", type: "select",
        options: [{ v: "none", l: "Nee, nog niets" }, { v: "informal", l: "Informele afspraken" }, { v: "draft", l: "In concept" }, { v: "active", l: "Vastgesteld en actief" }],
        scoring: { none: { orde: -3, avg: -2, aiact: -2 }, informal: { orde: -1, avg: -1, aiact: -1 }, draft: { orde: 1, avg: 1, aiact: 1 }, active: { orde: 3, avg: 2, aiact: 2 } } },
      { id: "org_review", text: "Wordt het AI-beleid periodiek ge\u00EBvalueerd en bijgewerkt?", type: "select",
        hint: "De NOvA beveelt een controlecyclus aan. Het College van Toezicht zal AI-gebruik vanaf 2026 als expliciet aandachtspunt meenemen.",
        options: [{ v: "none", l: "Nee / niet van toepassing" }, { v: "ad_hoc", l: "Ad hoc, als er aanleiding is" }, { v: "triennial", l: "Ja, minimaal eens per drie jaar" }, { v: "annual", l: "Ja, minimaal jaarlijks" }],
        scoring: { none: { orde: -2, aiact: -1 }, ad_hoc: { orde: 0, aiact: 0 }, triennial: { orde: 1, aiact: 1 }, annual: { orde: 2, aiact: 2 } } },
    ] },

  { id: "usage", title: "AI-gebruik & Toolselectie", icon: "\uD83E\uDD16",
    subtitle: "Welke AI-tools worden er gebruikt en hoe?",
    questions: [
      { id: "usage_tools", text: "Welke tools stelt uw organisatie aan de medewerkers ter beschikking?", type: "multi_with_other",
        options: [
          { v: "zeno", l: "Zeno" },
          { v: "andri", l: "Andri.ai" },
          { v: "legalmike", l: "LegalMike" },
          { v: "genial", l: "GenIA-L" },
          { v: "legalfly", l: "LEGALFLY" },
          { v: "lexboost", l: "Lexboost" },
          { v: "legalmind", l: "Legal Mind" },
          { v: "lexgen", l: "LEXGEN AI" },
          { v: "saga", l: "Saga" },
          { v: "harvey", l: "Harvey" },
          { v: "newcode", l: "Newcode" },
          { v: "luminance", l: "Luminance" },
          { v: "legora", l: "Legora" },
          { v: "cocounsel", l: "CoCounsel (Thomson Reuters)" },
          { v: "lexis_ai", l: "Lexis+ AI" },
          { v: "westlaw", l: "Westlaw Edge / Precision" },
          { v: "spellbook", l: "Spellbook" },
          { v: "chatgpt", l: "ChatGPT" },
          { v: "claude", l: "Claude" },
          { v: "copilot", l: "Microsoft Copilot" },
          { v: "gemini", l: "Gemini" },
          { v: "perplexity", l: "Perplexity" },
          { v: "fireflies", l: "Fireflies" },
          { v: "gamma", l: "Gamma" },
          { v: "klang", l: "Klang" },
          { v: "none", l: "Geen / nog niet" },
          { v: "other", l: "Anders, namelijk\u2026" },
        ] },
      { id: "usage_tier", text: "Zijn er onder die tools, tools die gratis zijn en die worden gebruikt voor werkgerelateerde taken?", type: "select",
        hint: "Bij gratis versies wordt input standaard gebruikt voor modeltraining. De NOvA waarschuwt expliciet: gebruik geen gratis tools voor vertrouwelijke informatie.",
        options: [{ v: "yes_conf", l: "Ja, ook met vertrouwelijke informatie" }, { v: "yes_general", l: "Ja, maar alleen voor algemene taken" }, { v: "no_paid", l: "Nee, alleen betaalde / enterprise versies" }, { v: "no_none", l: "Nee, er worden geen gratis AI-tools gebruikt" }],
        scoring: { yes_conf: { orde: -3, avg: -3 }, yes_general: { orde: -1, avg: -1 }, no_paid: { orde: 2, avg: 1 }, no_none: { orde: 0, avg: 0 } } },
      { id: "usage_purposes", text: "Waarvoor wordt AI ingezet?", type: "multi",
        options: [
          { v: "research", l: "Juridisch onderzoek" },
          { v: "drafting", l: "Processtukken opstellen" },
          { v: "contracts", l: "Contracten maken" },
          { v: "email", l: "Mails opstellen" },
          { v: "review", l: "Document review / DD" },
          { v: "summary", l: "Samenvatten" },
          { v: "translation", l: "Vertalen" },
          { v: "admin", l: "Administratief" },
        ] },
      { id: "usage_data", text: "Welke gegevens worden ingevoerd in AI-tools?", type: "multi",
        options: [
          { v: "none", l: "Geen persoonsgegevens of vertrouwelijke data" },
          { v: "anon", l: "Geanonimiseerde of gepseudonimiseerde gegevens" },
          { v: "names", l: "Namen en contactgegevens van cli\u00EBnten" },
          { v: "case", l: "Dossierstukken en procesinformatie" },
          { v: "financial", l: "Financi\u00EBle gegevens" },
          { v: "sensitive", l: "Bijzondere persoonsgegevens (gezondheid, straf, etc.)" },
          { v: "strategy", l: "Interne kantoorstrategie of bedrijfsgevoelige informatie" },
          { v: "unknown", l: "Onbekend / geen zicht op" },
        ] },
      { id: "usage_shadow", text: "Worden er naast de door de organisatie uitgerolde AI-tools door medewerkers ook nog andere tools gebruikt?", type: "select",
        hint: "Gebruik van niet-goedgekeurde tools (\u2018shadow IT\u2019) vormt een privacy- en beveiligingsrisico.",
        options: [
          { v: "no", l: "Nee, medewerkers gebruiken uitsluitend de door ons uitgerolde tools" },
          { v: "unknown", l: "Onbekend, daar hebben we geen zicht op" },
          { v: "likely", l: "Waarschijnlijk wel, maar we sturen er niet op" },
          { v: "yes_tolerated", l: "Ja, dat is bekend en wordt gedoogd" },
          { v: "yes_policy", l: "Ja, maar hier geldt een duidelijk beleid voor" },
        ],
        scoring: { no: { orde: 2, avg: 2 }, unknown: { orde: -2, avg: -2 }, likely: { orde: -1, avg: -1 }, yes_tolerated: { orde: -3, avg: -3 }, yes_policy: { orde: 1, avg: 1 } } },
      { id: "usage_control", text: "Op welke wijze is geborgd dat medewerkers geen gevoelige gegevens invoeren in tools die daarvoor niet zijn ingericht of goedgekeurd?", type: "select",
        hint: "Denk aan technische maatregelen, beleid, training of een combinatie daarvan.",
        options: [
          { v: "none", l: "Daar is geen specifieke borging voor" },
          { v: "awareness", l: "Via bewustwording en instructie (geen technische afdwinging)" },
          { v: "policy", l: "Via vastgesteld beleid met gedragsregels" },
          { v: "technical", l: "Via technische maatregelen (bijv. DLP, toegangsbeperking)" },
          { v: "combined", l: "Combinatie van beleid, training \u00E9n technische maatregelen" },
        ],
        scoring: { none: { orde: -3, avg: -3 }, awareness: { orde: -1, avg: -1 }, policy: { orde: 0, avg: 0 }, technical: { orde: 1, avg: 1 }, combined: { orde: 3, avg: 3 } } },
      { id: "aiact_exit", text: "Heeft uw kantoor een exitstrategie voor AI-leveranciers (ter voorkoming van vendor lock-in)?", type: "select",
        hint: "De AP waarschuwt voor afhankelijkheid van niet-EU leveranciers en benadrukt het belang van een exitstrategie en alternatieven.",
        options: [{ v: "none", l: "Nee, niet over nagedacht" }, { v: "aware", l: "Ja, maar niet uitgewerkt" }, { v: "plan", l: "Ja, concrete exitstrategie beschikbaar" }],
        scoring: { none: { aiact: -2, avg: -1 }, aware: { aiact: 0, avg: 0 }, plan: { aiact: 2, avg: 1 } } },
      { id: "aiact_literacy", text: "Is uw kantoor op de hoogte van de AI-geletterdheidsverplichting uit art. 4 AI Act?", type: "select",
        hint: "Dit is de eerste verplichting die van kracht is. Iedereen die AI-systemen inzet moet over een passend niveau van AI-geletterdheid beschikken.",
        options: [{ v: "unaware", l: "Nee, niet van op de hoogte" }, { v: "aware", l: "Ja, maar nog geen actie ondernomen" }, { v: "compliant", l: "Ja, en we voldoen hieraan" }],
        scoring: { unaware: { aiact: -3 }, aware: { aiact: -1 }, compliant: { aiact: 3 } } },
    ] },

  { id: "data", title: "Data & Privacy", icon: "\uD83D\uDD12",
    subtitle: "Hoe gaat uw kantoor om met persoonsgegevens en AI-leveranciers?",
    questions: [
      { id: "data_register", text: "Is er een verwerkingsregister (art. 30 AVG) dat ook AI-tools omvat?", type: "select",
        options: [{ v: "none", l: "Nee" }, { v: "partial", l: "Gedeeltelijk / verouderd / zonder AI-tools" }, { v: "yes", l: "Ja, actueel en inclusief AI-verwerkingen" }],
        scoring: { none: { avg: -3 }, partial: { avg: -1 }, yes: { avg: 3 } } },
      { id: "data_dpia", text: "Is er een DPIA uitgevoerd voor AI-gebruik?", type: "select",
        hint: "De AP stelt: een DPIA is verplicht zodra AI wordt ingezet bij verwerking van persoonsgegevens. Bij hoog risico is voorafgaande raadpleging verplicht.",
        options: [{ v: "none", l: "Nee" }, { v: "planned", l: "Gepland" }, { v: "partial", l: "Ja, voor sommige tools" }, { v: "yes", l: "Ja, voor alle AI-tools" }],
        scoring: { none: { avg: -3, aiact: -2 }, planned: { avg: -1, aiact: -1 }, partial: { avg: 1, aiact: 1 }, yes: { avg: 3, aiact: 2 } } },
      { id: "data_processor", text: "Zijn er verwerkersovereenkomsten gesloten met AI-leveranciers?", type: "select",
        options: [{ v: "none", l: "Nee / niet gecontroleerd" }, { v: "some", l: "Bij sommige leveranciers" }, { v: "all", l: "Ja, bij alle leveranciers" }],
        scoring: { none: { avg: -3 }, some: { avg: 0 }, all: { avg: 3 } } },
      { id: "data_vendor", text: "Controleert u contractvoorwaarden van AI-leveranciers (bijv. op aansprakelijkheid en subverwerkers)?", type: "select",
        hint: "De NOvA en AP benadrukken beide: ga niet af op marketingbeloften. Controleer zelf wat er met data gebeurt, welke subverwerkers betrokken zijn en wie aansprakelijk is.",
        options: [{ v: "none", l: "Nee / afgegaan op marketing" }, { v: "partial", l: "Globaal bekeken" }, { v: "yes", l: "Ja, juridisch getoetst" }],
        scoring: { none: { orde: -2, avg: -2 }, partial: { orde: 0, avg: 0 }, yes: { orde: 2, avg: 2 } } },
      { id: "data_transfer", text: "Weet u waar cli\u00EBntdata naartoe gaat wanneer het in een AI-tool wordt ingevoerd (verwerking, opslag, subverwerkers)?", type: "select",
        hint: "Let op: ook bij Europese hosting kan de CLOUD Act toegang geven aan Amerikaanse autoriteiten als de leverancier Amerikaans is.",
        options: [
          { v: "unknown", l: "Nee, dat is ons niet bekend" },
          { v: "partial", l: "Gedeeltelijk \u2014 we weten het van sommige tools" },
          { v: "yes_outside_eea", l: "Ja, data wordt buiten de EER verwerkt (met of zonder waarborgen)" },
          { v: "yes_eea", l: "Ja, verwerking vindt plaats binnen de EER bij een niet-Amerikaanse leverancier" },
        ],
        scoring: { unknown: { avg: -2 }, partial: { avg: -1 }, yes_outside_eea: { avg: 0 }, yes_eea: { avg: 3 } } },
      { id: "data_training", text: "Wordt uw data gebruikt voor AI-modeltraining?", type: "select",
        options: [{ v: "unknown", l: "Onbekend" }, { v: "yes", l: "Ja / mogelijk" }, { v: "opted_out", l: "Nee, opt-out ingesteld" }, { v: "contractual", l: "Nee, contractueel uitgesloten" }],
        scoring: { unknown: { avg: -2, orde: -1 }, yes: { avg: -3, orde: -2 }, opted_out: { avg: 1, orde: 1 }, contractual: { avg: 3, orde: 2 } } },
      { id: "data_implicit", text: "Bent u zich ervan bewust dat de optelsom van AI-gesprekken over tijd een gedetailleerd beeld kan vormen van dossiers, cli\u00EBnten en kantoorstrategie?", type: "select",
        hint: "Niet alleen de tekst die u invoert wordt verwerkt. AI-tools slaan gespreksgeschiedenissen op en kunnen zo cumulatief gevoelige patronen blootleggen.",
        options: [{ v: "unaware", l: "Nee, niet eerder bij stilgestaan" }, { v: "aware", l: "Ja, maar geen maatregelen genomen" }, { v: "mitigated", l: "Ja, en we hebben maatregelen genomen (bijv. geen gespreksgeschiedenis, aparte accounts)" }],
        scoring: { unaware: { orde: -2, avg: -2 }, aware: { orde: -1, avg: -1 }, mitigated: { orde: 2, avg: 2 } } },
      { id: "data_breach", text: "Welke van de volgende situaties beschouwt u als een datalek?", type: "multi",
        hint: "De AP signaleert een stijging van datalekken gerelateerd aan generatieve AI. Selecteer alle situaties die u als meldplichtig datalek zou beschouwen.",
        options: [
          { v: "hack", l: "Een hacker krijgt toegang tot ons systeem" },
          { v: "email", l: "Een e-mail met persoonsgegevens wordt naar de verkeerde ontvanger gestuurd" },
          { v: "ai_conf", l: "Vertrouwelijke cli\u00EBntdata wordt ingevoerd in een niet-goedgekeurde AI-tool" },
          { v: "ai_training", l: "Cli\u00EBntdata blijkt gebruikt te zijn voor AI-modeltraining" },
          { v: "ai_cumulative", l: "AI-gespreksgeschiedenissen bevatten cumulatief gevoelige dossierinformatie" },
          { v: "none", l: "Geen van bovenstaande situaties" },
        ] },
    ] },

  { id: "prof", title: "Tuchtrecht", icon: "\uD83D\uDCDC",
    subtitle: "Hoe verhoudt uw AI-gebruik zich tot de vijf NOvA-kernwaarden?",
    questions: [
      { id: "prof_conf", text: "Hoe waarborgt u de geheimhoudingsplicht bij AI-gebruik?", type: "select",
        options: [{ v: "none", l: "Geen specifieke maatregelen" }, { v: "guidelines", l: "Interne richtlijnen" }, { v: "technical", l: "Technisch (enterprise, API, anonimisering)" }, { v: "both", l: "Richtlijnen \u00E9n technische maatregelen" }],
        scoring: { none: { orde: -3 }, guidelines: { orde: 0 }, technical: { orde: 1 }, both: { orde: 3 } } },
      { id: "prof_supervision", text: "Vindt er menselijke controle plaats op AI-output voordat het naar cli\u00EBnten of derden gaat?", type: "select",
        options: [{ v: "no", l: "Niet structureel" }, { v: "important", l: "Alleen bij belangrijke stukken" }, { v: "always", l: "Altijd, standaardprocedure" }],
        scoring: { no: { orde: -3 }, important: { orde: 1 }, always: { orde: 3 } } },
      { id: "prof_verify", text: "Hoe wordt jurisprudentie en regelgeving uit AI-output geverifieerd?", type: "select",
        hint: "De NOvA benadrukt onder deskundigheid: de advocaat blijft verantwoordelijk voor de juistheid van AI-output. Bronverwijzingen uit een AI-tool zijn een nuttig startpunt, maar vereisen actieve inhoudelijke controle.",
        options: [
          { v: "no", l: "Niet structureel \u2014 bronnen worden niet separaat nagelopen" },
          { v: "tool_reviewed", l: "Via de bronverwijzingen die de AI-tool aanreikt, met inhoudelijke beoordeling door de advocaat" },
          { v: "independent", l: "Via onafhankelijke bronnen (rechtspraak.nl, wetten.nl, Kluwer Navigator, etc.)" },
          { v: "combined", l: "Combinatie \u2014 toolbronnen als startpunt, aangevuld met onafhankelijke verificatie waar nodig" },
        ],
        scoring: { no: { orde: -3 }, tool_reviewed: { orde: 1 }, independent: { orde: 2 }, combined: { orde: 2 } } },
      { id: "prof_disclosure", text: "Informeert u cli\u00EBnten over het AI-beleid van uw kantoor?", type: "select",
        hint: "De NOvA beveelt onder integriteit aan: informeer cli\u00EBnten over het AI-beleid van het kantoor. Dit is iets anders dan toestemming vragen per dossier.",
        options: [{ v: "never", l: "Nee" }, { v: "on_request", l: "Alleen op verzoek" }, { v: "policy", l: "Ja, via kantoorbeleid / algemene voorwaarden" }, { v: "proactive", l: "Ja, proactief bij iedere cli\u00EBnt" }],
        scoring: { never: { orde: -2 }, on_request: { orde: 0 }, policy: { orde: 1 }, proactive: { orde: 2 } } },
      { id: "prof_consent", text: "Vraagt u cli\u00EBnten vooraf toestemming voor AI-gebruik in hun specifieke dossier?", type: "select",
        hint: "De NOvA beveelt onder vertrouwelijkheid aan: vraag cli\u00EBnten om toestemming voordat AI wordt ingezet in hun dossier.",
        options: [{ v: "never", l: "Nee" }, { v: "sometimes", l: "Soms, bij invoer van cli\u00EBntgegevens" }, { v: "always", l: "Ja, standaard" }],
        scoring: { never: { orde: -3 }, sometimes: { orde: 1 }, always: { orde: 3 } } },
      { id: "prof_training", text: "Hoe is het AI-kennisniveau (AI-geletterdheid) van medewerkers geborgd?", type: "select",
        hint: "Zowel de NOvA (kernwaarde deskundigheid) als de AI Act (art. 4, verplicht sinds feb 2025) vereisen een passend niveau van AI-geletterdheid.",
        options: [{ v: "none", l: "Geen training of opleiding" }, { v: "ad_hoc", l: "Incidenteel / ad hoc" }, { v: "basic", l: "Basistraining gevolgd" }, { v: "structured", l: "Structureel programma (prompting, bias, risico\u2019s, hallucinaties)" }],
        scoring: { none: { orde: -2, aiact: -2 }, ad_hoc: { orde: 0, aiact: 0 }, basic: { orde: 1, aiact: 1 }, structured: { orde: 2, aiact: 3 } } },
    ] },
];
