// PRODUCTIE-VERSIE — deze wordt gebruikt door de edge function.
// Referentiekopie in src/config/prompts.js. Houd beide bestanden in sync.

export function buildPrompt(answers, scores, lang) {
  const ctx = `Antwoorden: ${JSON.stringify(answers)}
Scores: Orde ${scores.orde}/100, AVG ${scores.avg}/100, AI Act ${scores.aiact}/100, Overall ${scores.overall}/100.`;

  if (lang === "nl") {
    return `Je kent de volgende bronnen voor het beoordelen van AI-gebruik in de advocatuur:

1. NOvA Aanbevelingen AI (nov 2025): vijf kernwaarden (deskundigheid, vertrouwelijkheid, onafhankelijkheid, integriteit, partijdigheid). Aanbevelingen: AI-geletterdheid borgen, output altijd verifi\u00EBren met bronvermelding, GEEN gratis tools voor vertrouwelijk, cli\u00EBnttoestemming vragen per dossier, cli\u00EBnten informeren over kantoor-AI-beleid (integriteit), documentatie afwegingen, DPIA uitvoeren, controlecyclus, kantoorbreed beleid. College van Toezicht: AI-gebruik vanaf 2026 expliciet aandachtspunt bij dekenale gesprekken.

2. AP Verantwoord Vooruit (feb 2026): begin bij "wat is acceptabel", niet bij "wat kan technisch". Geen black-box systemen. Datalekken door GenAI stijgen. AVG geldt hele GenAI-keten. Exitstrategie verplicht tegen vendor lock-in. DPIA verplicht bij AI+persoonsgegevens. Handreiking AVG-aspecten GenAI volgt april 2026.

3. EU AI Act: art. 4 AI-geletterdheid verplicht sinds feb 2025. Aug 2026: hoog-risico systemen + transparantie-eisen. Aug 2027: volledige inwerkingtreding. Toezicht: AP co\u00F6rdinerend.

4. Toolkennis (bron: ICTRecht onderzoek nov. 2025 + eigen kennis): De volgende tools zijn juridisch-specifieke oplossingen voor de Nederlandse markt, onderzocht door ICTRecht. Alle 9 verwerken data binnen de EER en gebruiken klantdata NIET voor modeltraining: Andri.ai, LEXGEN AI, LegalMike, GenIA-L, Legal Mind, Saga, LEGALFLY, Lexboost, Zeno. Ook de volgende juridische tools voldoen doorgaans aan strikte privacy- en beveiligingseisen: Harvey, Newcode, Luminance, Legora, CoCounsel, Lexis+ AI, Westlaw Edge/Precision, Spellbook. De volgende tools zijn algemene AI-tools waarbij het veiligheidsniveau sterk afhangt van het abonnementstype en de configuratie: ChatGPT, Claude, Microsoft Copilot, Gemini, Perplexity. Gratis versies van deze tools gebruiken input standaard voor modeltraining. Klang is een Europese (Zweedse) AI-transcriptietool die zich expliciet richt op de juridische markt, met ISO 27001, ISO 42001, AI Act-compliance en GDPR als uitgangspunt; data wordt verwerkt in Europa en niet gebruikt voor modeltraining. Fireflies is een Amerikaanse AI-transcriptietool met SOC 2 Type II en GDPR-compliance, maar als Amerikaans bedrijf is de CLOUD Act relevant. Gamma is een Amerikaanse AI-presentatietool; volgens het privacybeleid mag data worden gebruikt voor modeltraining tenzij contractueel anders is afgesproken.

${ctx}

Schrijf een professioneel compliance-rapport (Nederlands) met ## koppen:

BEKNOPTHEID EN TOKENLIMIET:
Schrijf het volledige rapport in maximaal 2000 woorden. Bij kantoren met 4 of meer AI-tools: maximaal 2500 woorden. Houd je aan de volgende limieten per sectie:
- Samenvatting: geen limiet op het aantal bulletpoints
- NOvA / AVG / AI Act secties: schrijf elke bevinding als maximaal twee zinnen \u2014 \u00E9\u00E9n constatering, \u00E9\u00E9n aanbeveling. Als een bevinding identiek is aan een punt in een eerdere sectie, laat deze weg
- Top 5 Prioriteiten: elke prioriteit maximaal 3 zinnen
Vermijd contextuele uitleg die de lezer al kent. Schrijf niet waar\u00F3m een regel bestaat, schrijf w\u00E1t het kantoor moet doen.

TOON:
Erken altijd eerst wat het kantoor goed doet voordat je lacunes benoemt. Bij kantoren met lage scores: formuleer aanbevelingen als verbeterstappen, niet als waarschuwingen \u2014 het doel is het kantoor verder helpen, niet alarmeren. Bij kantoren met hoge scores: benoem de sterke punten expliciet en beperk aanbevelingen tot wat daadwerkelijk ontbreekt.

STRIKTE REGELS:
1. Verwijs NOOIT naar ICTRecht in het rapport \u2014 gebruik die kennis als achtergrond voor toolbeoordelingen maar citeer de bron niet. Voeg GEEN beweringen toe die niet op een van de drie bronnen (NOvA, AP, AI Act) zijn gebaseerd. Voeg GEEN bronverwijzingen, URLs of klikbare links toe aan het rapport.
2. Beoordeel het gebruik van gratis tools UITSLUITEND op basis van het antwoord op vraag usage_tier. Als de gebruiker heeft aangegeven dat alleen betaalde of enterprise versies worden gebruikt (no_paid), mag je NIET concluderen of suggereren dat er gratis tools worden ingezet, ook niet als tools als ChatGPT of Claude zijn aangevinkt bij usage_tools. De toolnaam zegt niets over het abonnementstype.
3. Als usage_tier = yes_general (gratis tools alleen voor algemene taken), mag je NIET concluderen dat vertrouwelijke of zaaksgerelateerde informatie in gratis tools wordt ingevoerd. De vraag over welke data wordt ingevoerd (usage_data) geldt voor het totale AI-gebruik, niet specifiek voor de gratis tools.
4. Verwijs bij toolbeoordelingen expliciet naar wat de gebruiker heeft ingevuld, niet naar algemene veronderstellingen over de tool.
5. TOON bij gratis tools: adviseer NIET om gratis tools volledig te verbieden of technisch te blokkeren. Advocaten zijn vaardige professionals die zelf verantwoorde afwegingen kunnen maken, mits zij goed ge\u00EFnformeerd zijn over de risico\u2019s. Adviseer in plaats daarvan: stel heldere kaders en zorg dat professionals de risico\u2019s begrijpen van welke data wel en niet geschikt is voor gebruik in gratis tools. De eigen verantwoordelijkheid van de advocaat staat centraal.
7. TOON bij bronverificatie: de NOvA stelt dat de advocaat verantwoordelijk blijft voor de juistheid van AI-output. Bronverwijzingen die een tool aanreikt zijn een nuttig startpunt en mogen worden gebruikt, maar vereisen actieve inhoudelijke controle door de advocaat \u2014 niet als formaliteit maar als professioneel oordeel. Schrijf NIET dat bronverwijzingen uit de tool per definitie onvoldoende zijn. Schrijf ook NIET dat zwaardere verificatieplichten gelden voor specifieke rechtsgebieden zoals fiscaal recht of M&A, tenzij de NOvA dat expliciet stelt.
8. SCOPE: Het rapport mag UITSLUITEND gebaseerd zijn op (a) de ingevulde antwoorden en (b) de vier genoemde bronnen (NOvA, AP, EU AI Act, ICTRecht). Gebruik je eigen algemene kennis NIET om conclusies te trekken, risico\u2019s te benoemen of aanbevelingen te doen die niet direct voortvloeien uit een combinatie van een concreet antwoord \u00E9n een van de vier bronnen. Vul niet aan op basis van rechtsgebieden, kantoorgrootte of andere contextuele informatie die niet expliciet door de gebruiker als probleem is aangemerkt.
9. ONDERWERPEN DIE NIET IN DE VRAGENLIJST ZITTEN: Als een onderwerp niet bevraagd is, mag het NIET in het rapport verschijnen \u2014 ook niet als suggestie of aandachtspunt. Bias is bijvoorbeeld uit de vragenlijst verwijderd en mag dus nergens in het rapport worden genoemd, ook niet in de context van rechtsgebieden zoals M&A of fiscaal recht.
10. TRAININGSNIVEAU: Doe GEEN uitspraken over of een bepaald trainingsniveau (bijv. basistraining) al dan niet toereikend is voor specifieke toepassingen zoals drafting, review of juridisch onderzoek. De bronnen geven geen concrete criteria per taaktype. Constateer uitsluitend wat de gebruiker heeft ingevuld en wat de bronnen voorschrijven (art. 4: "passend niveau", NOvA: "essentieel voor iedere advocaat"), zonder zelf te beoordelen of het huidige niveau voldoet voor de opgegeven toepassingen.
11. TOOLKENNIS EN GELETTERDHEID: De AI-geletterdheidsverplichting (art. 4 AI Act) ziet op conceptuele AI-kennis: begrip van hoe AI werkt, risico\u2019s, hallucinaties, regelgeving. Kennis van de specifieke tools die het kantoor inzet valt onder de NOvA-kernwaarde deskundigheid \u2014 wie een tool gebruikt, moet begrijpen wat die tool doet met data, hoe betrouwbaar de output is en waar de beperkingen liggen. Vermeng deze twee niet. Schrijf GEEN aanbevelingen voor formele, jaarlijks terugkerende toolspecifieke trainingsprogramma\u2019s tenzij de bronnen die vorm voorschrijven. De bronnen schrijven het DOEL voor (passend kennisniveau), niet de VORM (de wijze waarop het kantoor dat borgt is aan het kantoor zelf).
12. GEEN EXTRAPOLATIE NAAR TOEPASSINGEN: Koppel antwoorden NIET aan elkaar om zelf risico-inschattingen te maken die niet in de bronnen staan. Voorbeelden van wat NIET mag: (a) Als een kantoor AI inzet voor drafting \u00E9n een basistraining heeft gevolgd, concludeer NIET dat het trainingsniveau ontoereikend is voor die toepassing. (b) Als een kantoor betaalde/enterprise versies gebruikt (usage_tier = no_paid) \u00E9n gevoelige data invoert (usage_data), presenteer die combinatie NIET als risico \u2014 enterprise versies zijn juist bedoeld voor die inzet. (c) Als een kantoor bepaalde toepassingen heeft aangevinkt (usage_purposes), gebruik die NIET om de toon van het rapport alarmerender te maken dan de feitelijke antwoorden rechtvaardigen. Beoordeel elk antwoord op zijn eigen merites tegen de bronnen, niet via geconstrueerde kruisverbanden.
13. TOOLBEOORDELING: Het rapport MOET een concrete beoordeling bevatten van de tools die de gebruiker heeft aangevinkt bij usage_tools. Gebruik hiervoor de toolkennis uit bron 4. Categoriseer de geselecteerde tools en benoem het POSITIEF als een kantoor bewust kiest voor betaalde, juridisch-specifieke of professionele tools. Het rapport moet niet alleen risico\u2019s signaleren maar ook erkennen waar een kantoor goede keuzes maakt. Beoordeel elke tool op basis van de feitelijke informatie uit bron 4, NIET op basis van een generieke categorielabel. Als een tool (bijv. Klang) in bron 4 wordt beschreven als Europees, ISO-gecertificeerd en juridisch geori\u00EBnteerd, beoordeel deze dan op die feiten \u2014 concludeer NIET dat de tool "ongeschikt" is of "aanvullende due diligence vereist" als de bronnen dat niet stellen.
14. NAAMGEVING: Schrijf het rapport vanuit het perspectief van de lezer. Gebruik "uw organisatie" of "uw kantoor" — NIET "dit kleine kantoor", "dit grote kantoor" of andere grootte-aanduidingen. Schrijf altijd "Nederlandse Orde van Advocaten" bij eerste vermelding. Daarna mag worden verkort naar "de Orde". Schrijf NOOIT "Orde van Advocaten" zonder "Nederlandse".
15. FORMATTING: Begin het rapport DIRECT met de sectie ## Samenvatting. Schrijf GEEN rolbeschrijving, meta-header, titel of inleidende zin boven de samenvatting. Geen tekst als "Rapportage: Senior AI-compliance adviseur" of "AI-compliance rapport" of iets dergelijks.
16. NIET AANSCHERPEN VOORBIJ DE BRON: Geef alleen aanbevelingen die letterlijk in de bronnen staan. Vul niet in w\u00E1t er gedocumenteerd moet worden, welke certificeringen moeten worden gevraagd, of hoe training moet worden vormgegeven. Stel geen termijnen, deadlines of tijdschema\u2019s die niet in de bronnen staan. Voorbeelden van wat NIET mag: (a) "documenteer welke tool, voor welk doel, en hoe verificatie heeft plaatsgevonden" \u2192 de bronnen zeggen alleen "documenteer afwegingen". (b) "organiseer binnen drie maanden een trainingssessie" \u2192 de bronnen zeggen alleen "passend niveau van AI-geletterdheid". (c) "stel binnen twee maanden een exitstrategie op" \u2192 de bronnen zeggen alleen "ontwikkel een exitstrategie". (d) "controleer of leveranciers voldoen aan ISO 27001, SOC 2" \u2192 de bronnen zeggen alleen "voer leverancierscontrole uit". Houd je aan de formulering en het abstractieniveau van de bron zelf.
18. BLACK-BOX PASSAGE: De AP-passage over black-box systemen en uitlegbaarheid is NIET van toepassing op advocatenkantoren die AI als hulpmiddel inzetten. Neem deze NIET op \u2014 ook niet als alinea binnen een andere sectie, ook niet als milde verwijzing naar transparantie van de onderliggende werking, en ook niet bij leverancierscontrole of due diligence.
19. RELEVANTIEFILTER AP EN AI ACT: De AP en de AI Act richten zich op alle organisaties, niet specifiek op de advocatuur. Toets ELKE passage uit deze bronnen op relevantie voor een advocatenkantoor dat AI als hulpmiddel inzet (niet als ontwikkelaar of inzetter van autonome besluitvorming). Passages die niet relevant zijn voor dit gebruik terzijde leggen en NIET opnemen in het rapport.

## Samenvatting
Beperk de samenvatting tot de positie en risico\u2019s van DIT SPECIFIEKE kantoor op basis van de ingevulde antwoorden. Geen generieke tijdlijnen, deadlines of achtergrondinformatie over regelgeving. Schrijf 2-3 zinnen over de huidige positie, gevolgd door een opsomming van de belangrijkste risico\u2019s als bullet points (gebruik "- " per risico). 
## Nederlandse Orde van Advocaten \u2014 Bevindingen & Aanbevelingen
Toets aan de vijf kernwaarden. Benoem specifiek: gratis tools (alleen als usage_tier dit aangeeft), verificatie/bronvermelding, cli\u00EBnttoestemming vs. informeren over beleid (dit zijn twee verschillende dingen), documentatie. Verwijs naar College van Toezicht 2026.

## AVG / GDPR \u2014 Bevindingen & Aanbevelingen
Toets: verwerkingsregister, DPIA, verwerkersovereenkomsten, leverancierscontrole, doorgifte/CLOUD Act, modeltraining, cumulatieve dataverzameling, datalekprocedure bij AI-incidenten. Verwijs naar AP Verantwoord Vooruit.

## EU AI Act \u2014 Bevindingen & Aanbevelingen
Toets: art. 4 AI-geletterdheid (al verplicht!), exitstrategie, voorbereiding aug 2026, College van Toezicht 2026. 
## Top 5 Prioriteiten
Genummerd 1. t/m 5. op urgentie (gebruik expliciete oplopende nummering: 1. 2. 3. 4. 5. \u2014 schrijf NIET vijf keer "1."). Per prioriteit: wat moet er gebeuren, waarom nu, welk risico wordt geadresseerd. Maximaal 3 zinnen per prioriteit.

Schrijf professioneel, concreet, geen bullets maar genummerde lijsten met expliciete oplopende nummering 1. 2. 3. etc. (behalve in de samenvatting). Vermijd algemeenheden \u2014 verwijs naar specifieke antwoorden.`;
  }

  return `You know the following sources for assessing AI use in law firms:

1. NOvA (Dutch Bar) AI Recommendations (Nov 2025): five core values (competence, confidentiality, independence, integrity, partisanship). Key: ensure AI literacy, always verify output with source citation, NEVER use free tools for confidential data, obtain client consent per matter, inform clients about firm AI policy (integrity vs consent are distinct), document decisions, conduct DPIA, review cycle, firm-wide policy. Supervisory Board: AI use explicit focus point from 2026.

2. Dutch DPA "Verantwoord Vooruit" (Feb 2026): start from "what is acceptable" not "what is technically possible". No black-box systems. Data breaches from GenAI rising. GDPR applies to entire GenAI chain. Exit strategy required against vendor lock-in. DPIA mandatory for AI+personal data.

3. EU AI Act: Art. 4 AI literacy mandatory since Feb 2025. Aug 2026: high-risk systems + transparency. Aug 2027: full effect. Supervision: Dutch DPA coordinating.

4. Tool knowledge (source: ICTRecht research Nov. 2025 + own knowledge): The following are legal-specific tools for the Dutch market, independently researched by ICTRecht. All 9 process data within the EEA and do NOT use client data for model training: Andri.ai, LEXGEN AI, LegalMike, GenIA-L, Legal Mind, Saga, LEGALFLY, Lexboost, Zeno. The following legal tools also generally meet strict privacy and security standards: Harvey, Newcode, Luminance, Legora, CoCounsel, Lexis+ AI, Westlaw Edge/Precision, Spellbook. The following are general-purpose AI tools where the safety level depends heavily on subscription type and configuration: ChatGPT, Claude, Microsoft Copilot, Gemini, Perplexity. Free versions of these tools use input for model training by default. Klang is a European (Swedish) AI transcription tool explicitly targeting the legal market, with ISO 27001, ISO 42001, AI Act compliance and GDPR as baseline; data is processed in Europe and not used for model training. Fireflies is an American AI transcription tool with SOC 2 Type II and GDPR compliance, but as a US company the CLOUD Act is relevant. Gamma is an American AI presentation tool; according to its privacy policy, data may be used for model training unless contractually agreed otherwise.

${ctx}

Write a professional compliance report (English) with ## headings:

BREVITY AND TOKEN LIMIT:
Write the full report in a maximum of 2000 words. For firms with 4 or more AI tools: maximum 2500 words. Adhere to the following limits per section:
- Executive Summary: no limit on bullet points
- NOvA / GDPR / AI Act sections: write each finding as a maximum of two sentences \u2014 one observation, one recommendation. If a finding is identical to a point in an earlier section, omit it
- Top 5 Priorities: each priority maximum 3 sentences
Avoid contextual explanation the reader already knows. Do not write WHY a rule exists, write WHAT the firm should do.

TONE:
Always acknowledge what the firm is doing well before identifying gaps. For firms with low scores: frame recommendations as improvement steps, not warnings \u2014 the goal is to help the firm move forward, not to alarm. For firms with high scores: explicitly name the strong points and limit recommendations to what is actually missing.

STRICT RULES:
1. NEVER reference ICTRecht in the report \u2014 use that knowledge as background for tool assessments but do not cite the source. Do NOT add any claims that are not based on one of the three sources (NOvA, AP, AI Act). Do NOT add source references, URLs or clickable links to the report.
2. Assess the use of free tools EXCLUSIVELY based on the answer to question usage_tier. If the user indicated that only paid or enterprise versions are used (no_paid), do NOT conclude or suggest that free tools are being used, even if tools like ChatGPT or Claude are checked in usage_tools. The tool name says nothing about the subscription type.
3. If usage_tier = yes_general (free tools for general tasks only), do NOT conclude that confidential or case-related information is entered into free tools. The question about which data is entered (usage_data) applies to overall AI usage, not specifically to the free tools.
4. When assessing tools, explicitly refer to what the user has filled in, not to general assumptions about the tool.
5. TONE on free tools: do NOT advise banning free tools outright or implementing technical blocks. Lawyers are skilled professionals capable of making responsible judgments, provided they are well informed about the risks. Instead advise: establish clear guidelines and ensure professionals understand which types of data are and are not appropriate for use in free tools. Professional autonomy and responsibility are central.
7. TONE on source verification: the NOvA states that the lawyer remains responsible for the accuracy of AI output. Source references provided by a tool are a useful starting point and may be used, but require active substantive review by the lawyer \u2014 not as a formality but as professional judgment. Do NOT write that source references from the tool are inherently insufficient. Do NOT write that heavier verification obligations apply to specific practice areas such as tax law or M&A, unless the NOvA explicitly states this.
8. SCOPE: The report may ONLY be based on (a) the answers provided and (b) the four named sources (NOvA, AP, EU AI Act, ICTRecht). Do NOT use your own general knowledge to draw conclusions, identify risks or make recommendations that do not directly follow from a combination of a specific answer and one of the four sources. Do not extrapolate based on practice areas, firm size or other contextual information that the user has not explicitly identified as a problem.
9. TOPICS NOT IN THE QUESTIONNAIRE: If a topic was not asked about, it may NOT appear in the report \u2014 not even as a suggestion or point of attention. Bias, for example, has been removed from the questionnaire and must therefore not appear anywhere in the report, including in the context of practice areas such as M&A or tax law.
10. TRAINING LEVEL: Do NOT make statements about whether a given training level (e.g. basic training) is sufficient or insufficient for specific applications such as drafting, review or legal research. The sources provide no concrete criteria per task type. Only state what the user has filled in and what the sources prescribe (Art. 4: "adequate level", NOvA: "essential for every lawyer"), without assessing whether the current level is adequate for the stated applications.
11. TOOL KNOWLEDGE AND LITERACY: The AI literacy obligation (Art. 4 AI Act) concerns conceptual AI knowledge: understanding how AI works, risks, hallucinations, regulation. Knowledge of the specific tools a firm uses falls under the NOvA core value of competence \u2014 whoever uses a tool must understand what that tool does with data, how reliable the output is, and where the limitations lie. Do not conflate these two. Do NOT recommend formal, annually recurring tool-specific training programs unless the sources prescribe that format. The sources prescribe the GOAL (adequate knowledge level), not the FORMAT (how the firm achieves this is up to the firm itself).
12. NO EXTRAPOLATION TO APPLICATIONS: Do NOT combine answers to construct risk assessments not supported by the sources. Examples of what is NOT allowed: (a) If a firm uses AI for drafting AND has completed basic training, do NOT conclude the training level is inadequate for that application. (b) If a firm uses paid/enterprise versions (usage_tier = no_paid) AND enters sensitive data (usage_data), do NOT present that combination as a risk \u2014 enterprise versions are designed for exactly that use. (c) If a firm has selected certain applications (usage_purposes), do NOT use those to make the report's tone more alarming than the actual answers warrant. Assess each answer on its own merits against the sources, not through constructed cross-references.
13. TOOL ASSESSMENT: The report MUST contain a concrete assessment of the tools the user selected in usage_tools. Use the tool knowledge from source 4. Categorize the selected tools and note it POSITIVELY when a firm deliberately chooses paid, legal-specific or professional tools. The report should not only flag risks but also acknowledge where a firm makes good choices. Assess each tool based on the factual information in source 4, NOT based on a generic category label. If a tool (e.g. Klang) is described in source 4 as European, ISO-certified and legally oriented, assess it on those facts \u2014 do NOT conclude the tool is "unsuitable" or "requires additional due diligence" unless the sources state this.
14. NAMING: Write the report from the reader's perspective. Use "your organisation" or "your firm" — NOT "this small firm", "this large firm" or other size labels. Always write "Dutch Bar Association (NOvA)" at first mention. Thereafter it may be shortened to "the NOvA" or "the Bar Association". Never write just "Bar Association" without "Dutch" at first mention.
15. FORMATTING: Start the report DIRECTLY with the section ## Executive Summary. Do NOT write a role description, meta-header, title or introductory sentence above the summary. No text such as "Report: Senior AI compliance advisor" or "AI compliance report" or anything similar.
16. DO NOT SHARPEN BEYOND THE SOURCE: Only give recommendations that are literally stated in the sources. Do not fill in WHAT should be documented, which certifications should be requested, or how training should be designed. Do not set deadlines or timelines not in the sources. Examples of what is NOT allowed: (a) "document which tool, for what purpose, and how verification was performed" \u2192 the sources only say "document decisions". (b) "organize a training session within three months" \u2192 the sources only say "adequate level of AI literacy". (c) "establish an exit strategy within two months" \u2192 the sources only say "develop an exit strategy". (d) "verify that vendors comply with ISO 27001, SOC 2" \u2192 the sources only say "conduct vendor assessment". Stick to the wording and level of abstraction of the source itself.
18. BLACK-BOX PASSAGE: The DPA passage about black-box systems and explainability does NOT apply to law firms using AI as a tool. Do NOT include it \u2014 not as a paragraph within another section, not as a mild reference to transparency of underlying workings, and not in vendor assessment or due diligence context.
19. RELEVANCE FILTER DPA AND AI ACT: The DPA and the AI Act target all organizations, not specifically the legal profession. Test EVERY passage from these sources for relevance to a law firm that uses AI as a tool (not as a developer or deployer of autonomous decision-making). Set aside and do NOT include passages that are not relevant to this use.

## Executive Summary
Limit the summary to the position and risks of THIS SPECIFIC firm based on the answers provided. No generic timelines, deadlines or background information about regulation. Write 2-3 sentences about the current position, followed by a list of the key risks as bullet points (use "- " per risk). 
## Dutch Bar Association (NOvA) \u2014 Findings & Recommendations
Assess against the five core values. Specifically address: free tools (only if usage_tier indicates this), verification/source citation, client consent vs. policy disclosure (these are two different things), documentation. Reference Supervisory Board 2026.

## GDPR \u2014 Findings & Recommendations
Assess: processing register, DPIA, processor agreements, vendor assessment, transfers/CLOUD Act, model training, cumulative data collection, breach procedures. Reference DPA Verantwoord Vooruit.

## EU AI Act \u2014 Findings & Recommendations
Assess: Art. 4 AI literacy (already mandatory!), exit strategy, Aug 2026 preparation, Supervisory Board 2026. 
## Top 5 Priorities
Numbered 1. through 5. by urgency (use explicit ascending numbering: 1. 2. 3. 4. 5. \u2014 do NOT write "1." five times). Per priority: what needs to happen, why now, which risk is addressed. Maximum 3 sentences per priority.

Professional, concrete, numbered lists with explicit ascending numbering 1. 2. 3. etc. not bullets (except in the summary). Reference specific answers.`;
}
